# Generated by Django 5.2.5 on 2025-10-29 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attribute", "0055_assignedvariantattributevalue_variant"),
        ("product", "0202_category_product_category_tree_id_lf1e1"),
    ]

    state_operations = [
        migrations.RemoveField(
            model_name="attributevariant",
            name="assigned_variants",
        ),
        migrations.AlterUniqueTogether(
            name="assignedvariantattributevalue",
            unique_together={("value", "variant")},
        ),
        migrations.AlterField(
            model_name="assignedvariantattributevalue",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributevalues",
                to="product.productvariant",
            ),
        ),
        migrations.RemoveField(
            model_name="assignedvariantattributevalue",
            name="assignment",
        ),
        migrations.DeleteModel(
            name="AssignedVariantAttribute",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignedvariantattributevalue",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="variantvalueassignment",
                to="attribute.AssignedVariantAttribute",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="assignedvariantattribute",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attributes",
                to="product.ProductVariant",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="assignedvariantattribute",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="variantassignments",
                to="attribute.AttributeVariant",
                null=True,
            ),
        ),
        # Remove FK constraints so that the DB doesn't try to truncate the references
        migrations.RunSQL(
            """
            ALTER TABLE attribute_assignedvariantattribute
            DROP CONSTRAINT IF EXISTS
            attribute_assignedva_assignment_id_5b9e4c71_fk_attribute;


            ALTER TABLE attribute_assignedvariantattribute
            DROP CONSTRAINT IF EXISTS
            attribute_assignedva_variant_id_a6f7b549_fk_product_p;


            ALTER TABLE attribute_assignedvariantattributevalue
            DROP CONSTRAINT IF EXISTS
            attribute_assignedva_assignment_id_040f7499_fk_attribute;


            ALTER TABLE attribute_assignedvariantattributevalue
            DROP CONSTRAINT IF EXISTS
            attribute_assignedva_value_id_4bbdc9fa_fk_attribute;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
    ]
